#!/bin/bash

ARGUMENTS="$@"
CWD=$(pwd)

# saner programming env: these switches turn some bugs into errors
set -o errexit -o pipefail -o noclobber -o nounset

umask 022

cp -r "${CWD}/input" "${CWD}/work"

cd "${CWD}/work"

npm install --ignore-scripts

PATH="$(npm bin):$PATH" prebuildify $ARGUMENTS

cp -r "${CWD}/work/prebuilds" "${CWD}/output/"
