#!/bin/bash

ARGUMENTS="$@"
CWD=$(pwd)
# https://stackoverflow.com/questions/59895/getting-the-source-directory-of-a-bash-script-from-within
DIRNAME=$(dirname "$0")

# with help from https://stackoverflow.com/a/29754866,

# saner programming env: these switches turn some bugs into errors
set -o errexit -o pipefail -o noclobber -o nounset

! getopt --test > /dev/null 
if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
    echo "Sorry, `getopt --test` failed in this environment."
    exit 1
fi

OPTIONS=hdi:o:n:a
LONGOPTS=help,docker,input:,output:,name:,arch:

# -use ! and PIPESTATUS to get exit code with errexit set
# -temporarily store output to be able to check for errors
# -activate quoting/enhanced mode (e.g. by writing out “--options”)
# -pass arguments only via   -- "$@"   to separate them correctly
! PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
    # e.g. return value is 1
    #  then getopt has complained about wrong arguments to stdout
    exit 2
fi
# read getopt’s output this way to handle the quoting right:
eval set -- "$PARSED"

HELP=n DOCKER=n
INPUT=- OUTPUT=- NAME=- ARCH=-
while true; do
    case "$1" in
        -h|--help)
            HELP=y
            shift
            ;;
        -d|--docker)
            DOCKER=y
            shift
            ;;
        -i|--input)
            INPUT="$2"
            shift 2
            ;;
        -o|--output)
            OUTPUT="$2"
            shift 2
            ;;
        -n|--name)
            NAME="$2"
            shift 2
            ;;
        -a|--arch)
            ARCH="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Programming error"
            exit 3
            ;;
    esac
done

DEBIAN_TRIPLET=-
GNU_TRIPLET=-

case $ARCH in
#  armel)
#    $DEBIAN_TRIPLET=arm-linux-gnueabi
#    ;;
#  armhf)
  arm)
    DEBIAN_TRIPLET=arm-linux-gnueabihf
    GNU_TRIPLET=arm-linux-gnueabihf
    ;;
  arm64)       
    DEBIAN_TRIPLET=aarch64-linux-gnu
    GNU_TRIPLET=aarch64-linux-gnu
    ;;
  *)              
esac 

if
  [ "${HELP}" == "y" ] || \
  [ "${INPUT}" == "-" ] || \
  [ "${OUTPUT}" == "-" ] || \
  [ "${ARCH}" == "-" ]
then
  cat >&2 <<EOF
Usage:
  prebuild-cross [options]

  Arguments:

    --arch <arch>: architecture - either arm or arm64
    --input <path>: required directory of input image spec
    --output <path>: required directory to output build results
    --name <name>: optional name of image

  Flags:

    -h, --help: show this usage
    -d, --docker: build image using docker

  Examples:

    prebuild-cross --docker --input ./examples/leveldown --output ./output
EOF
  exit 1
fi

if [ "${NAME}" == "-" ]
then
  NAME="$(basename "${INPUT}")"
fi

if [ "${DOCKER}" = "y" ]
then
  ./build-docker ${ARGUMENTS}
else
  umask 022
  mkdir -p "${CWD}/${OUTPUT}"
  rm -rf "${CWD}/${OUTPUT}/${NAME}"
  cd "${CWD}/${INPUT}"

  env -i LC_CTYPE=C.UTF-8 \
    PATH="$PATH" \
    npm install --ignore-scripts

  ${DEBIAN_TRIPLET}-gcc -v

  env -i LC_CTYPE=C.UTF-8 \
    PATH="$PATH" \
    SYSROOT=/usr/${DEBIAN_TRIPLET}/
    CPPPATH=/usr/${DEBIAN_TRIPLET}/include/
    LIBPATH=/usr/${DEBIAN_TRIPLET}/lib/
    PKG_CONFIG_PATH=/usr/${DEBIAN_TRIPLET}/lib/pkgconfig/
    AR=${DEBIAN_TRIPLET}-ar \
    AS=${DEBIAN_TRIPLET}-as \
    LD=${DEBIAN_TRIPLET}-ld \
    NM=${DEBIAN_TRIPLET}-nm \
    RANLIB=${DEBIAN_TRIPLET}-ranlib \
    STRIP=${DEBIAN_TRIPLET}-strip \
    CC=${DEBIAN_TRIPLET}-gcc \
    CXX=${DEBIAN_TRIPLET}-g++ \
    ARCH=${ARCH} \
    PREBUILD_ARCH=${ARCH} \
    PREBUILD_CONFIGURE_HOST=${GNU_TRIPLET} \
    npm run prebuild -- --arch=${ARCH}
  cp -r "${CWD}/${INPUT}" "${CWD}/${OUTPUT}/${NAME}"
  cd "${CWD}"
fi
